### ISSUE TITLE
a error happend when executing the scripts genrand under the folder /client/arraydb-client-0.88.4  

### ISSUE THREAD

**Issue by theseusyang** [exeray/jaguar#1]
when executing genrand.sh in  folder /client/arraydb-client-0.88.4, the following error will be happend:

./genrand: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./genrand)

the reason mainly is that GLIBC version is lower than  2.14.

**Comment by jonyue** [comment]
您好，
我们看看尽快给您解决。
谢谢

Jon

**Comment by jonyue** [comment]
Hi Theseus,

This should be fixed in new 0.88.5 version from github. Could you download it and try the new one?

Thanks
Jon
